### ISSUE TITLE
Постановка  второй (если считать отскакивание мячика от стен, то третьей) лабораторной работы

### ISSUE THREAD

**Issue by diper1998** [kozinove/java_pmi_2020#11]
Можете дать письменную постановку задачи, пожалуйста!

**Comment by kozinove** [comment]
Задача содержит 2 стадии:
Стадия 1. Подключается произвольное число пользователей.
Стадия 2. После подключения всех участников произвольный пользователь
ставит вопрос на голосование.
Вопрос предполагает бинарный ответ.
Вопрос рассылается всем участникам.
Каждый пользователь голосует либо за либо против.
После того как все проголосовали всем рассылается сумма за и против.
После голосования вторая стадия может повторяться.

--
С уважением,
Козинов Евгений
ННГУ


пт, 3 апр. 2020 г. в 13:56, Dima Perov <notifications@github.com>:

**Comment by diper1998** [comment]
Спасибо!
